# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print("The numpy version is: ")
print( np.__version__)
print("The numpy configuration is: ")
print(np.show_config())

The numpy version is: 
1.19.2
The numpy configuration is: 
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/calvi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/calvi/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/calvi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/calvi/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/calvi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/calvi/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/calvi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/calvi/anaconda3\\Library\\inc

**3. Create a 1D array of zeros of size 10 of type float32**

In [4]:
array = np.zeros((10), dtype = 'float32')
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [5]:
Z = np.zeros((32,12))
# Include your solution below
Z_mem = Z.size * Z.itemsize
print("The memory size of Z in bytes is: ", Z_mem)

The memory size of Z in bytes is:  3072


**5. Create a 1D array with values ranging from 10 to 58**

In [6]:
array = np.arange(10,59)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [7]:
a = np.arange(10)
# Include your solution below
a = a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [8]:
array = np.arange(9)
array = array.reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [9]:
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [10]:
Z = np.random.random((10,11))
print( "The oririginal array: \n", Z)
# Include your solution below
columnMaxes = np.amax(Z, axis = 0)
print("\n The max values for each column are: \n", columnMaxes)

The oririginal array: 
 [[0.2084848  0.23921031 0.71376719 0.7199855  0.73765395 0.7881934
  0.17551868 0.22378265 0.08248645 0.37769406 0.89646964]
 [0.87246367 0.14795304 0.43462882 0.04245509 0.55261564 0.19132561
  0.77392714 0.04259672 0.62776493 0.36832053 0.02181121]
 [0.52337552 0.12381194 0.60411339 0.03004482 0.82479966 0.10426402
  0.59578358 0.26206567 0.59218159 0.88863184 0.47506578]
 [0.35339019 0.42354722 0.27860888 0.92450533 0.42684221 0.47537368
  0.73957165 0.03230975 0.38245952 0.18135493 0.48652275]
 [0.35949074 0.62271458 0.88470644 0.93772408 0.92706863 0.07620733
  0.47822071 0.03330358 0.00864041 0.35967197 0.62214844]
 [0.18649492 0.61825854 0.83680889 0.18846632 0.66002531 0.8835496
  0.83427703 0.46646885 0.26961258 0.49494129 0.35765985]
 [0.93773044 0.99654853 0.32921372 0.16412236 0.74624047 0.94856105
  0.03026501 0.72800525 0.06636805 0.65434854 0.11518509]
 [0.54918364 0.58103255 0.73670565 0.38339348 0.61284664 0.77778775
  0.36420797 0.21359046 0.85

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [11]:
array = np.zeros((5,5))
H,W = array.shape
aux_array = np.ones((H+2, W+2))
aux_array[1:-1,1:-1] = array
print (aux_array)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [12]:
Z = np.ones((5,5))
# Include your solution below
padded_Z = np.pad(Z,(1,1))
print(padded_Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [26]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print(Z)
Z_int = np.around(Z).astype(int)
print(Z_int)

[3.82826676 6.1987982  5.37011405 9.94796417 3.87104076 1.57637903
 9.8618327  2.03086537 4.14494085 7.12535738]
[ 4  6  5 10  4  2 10  2  4  7]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [34]:
array = np.array([0,1,2,3,4])
T = np.tile(array, (5,1))
print(T)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [41]:
vec = np.linspace(0, 1, endpoint=False, num=11)[1:]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [53]:
vec = np.random.random((1,10))
print("The Random Vector: \n", vec)
sorted = np.sort(vec)
print("The Sorted Vector: \n", sorted)

The Random Vector: 
 [[0.88468086 0.67622085 0.32751647 0.95967733 0.78208113 0.56217872
  0.98732616 0.11689746 0.09599995 0.27663206]]
The Sorted Vector: 
 [[0.09599995 0.11689746 0.27663206 0.32751647 0.56217872 0.67622085
  0.78208113 0.88468086 0.95967733 0.98732616]]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [60]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
print("Cartesian Coordinates: \n", Z)
# Include your solution below
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
P = np.vstack((R, T)).T
print("\nPolar Coordinates: \n", P)

Cartesian Coordinates: 
 [[0.60074674 0.76042013]
 [0.51650553 0.2822757 ]
 [0.7417597  0.79038566]
 [0.44978738 0.76748407]
 [0.28491322 0.81194471]
 [0.96526148 0.55948668]
 [0.39775869 0.10612935]
 [0.70865065 0.37333892]
 [0.43009339 0.22478332]
 [0.17702978 0.59172041]]

Polar Coordinates: 
 [[0.96908999 0.90217074]
 [0.58860643 0.50016019]
 [1.08393585 0.81712469]
 [0.8895732  1.04069409]
 [0.86048228 1.23331795]
 [1.11568592 0.52530081]
 [0.41167392 0.26074407]
 [0.80097921 0.48488106]
 [0.48529152 0.48159388]
 [0.61763467 1.28009375]]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [66]:
vec = np.random.random((1,10))
M = np.amax(vec, axis=1)
print("Random Vector: \n", vec)
new_vec = np.where(np.isin(vec, M), 0, vec)
print("\nMax value Replaced with 0: \n", new_vec)

Random Vector: 
 [[0.60699781 0.53792872 0.02404199 0.34836666 0.16098117 0.25838318
  0.03853683 0.01636772 0.08701859 0.23695275]]

Max value Replaced with 0: 
 [[0.         0.53792872 0.02404199 0.34836666 0.16098117 0.25838318
  0.03853683 0.01636772 0.08701859 0.23695275]]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [98]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print("Original Array: \n", Z)
N = Z[abs(Z - z).argmin()]
print("\nClosest Value to ", z, ":", N)

Original Array: 
 [0.73313179 0.37935474 0.00395788 0.47852099 0.42775348 0.28578796
 0.71789892 0.57560619 0.704203   0.97164188]

Closest Value to  0.5 : 0.4785209887225774


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [112]:
Z = np.arange(6)[:0:-1]
# Include your solution below
print("Original Array: \n", Z)

Original Array: 
 [5 4 3 2 1]
Original Array: 
 [5 0 0 0 4 3 2 1]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below



**21. Swap the first and second rows of the 2D array below**

In [3]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution 
W[[1,0]] = W[[0,1]]
print(W)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [6]:
Z = np.random.randint(0,10,50)
print(Z)
# Include your solution below
count = np.bincount(Z)
print(np.argmax(count))

[9 2 3 9 2 1 2 0 7 6 1 0 5 5 5 4 8 6 3 5 7 8 4 2 9 3 4 4 4 0 8 0 7 4 9 7 4
 8 8 7 5 4 0 8 2 4 2 9 6 8]
4


**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    